### ISSUE TITLE
Fix Tests on py2.7 with matplotlib=1.1.1

### ISSUE THREAD

**Issue by jankatins** [yhat/ggpy#174]
Seems the only problem is this

```
======================================================================
ERROR: ggplot.tests.test_basic.test_stats_bin2d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/yhat/ggplot/ggplot/tests/test_basic.py", line 113, in test_stats_bin2d
    assert_same_ggplot(gg + stat_bin2d(), "stat_bin2d")
  File "/home/travis/build/yhat/ggplot/ggplot/tests/__init__.py", line 93, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/home/travis/build/yhat/ggplot/ggplot/tests/__init__.py", line 43, in _assert_same_ggplot_image
    fig = gg.draw()
  File "/home/travis/build/yhat/ggplot/ggplot/ggplot.py", line 290, in draw
    callbacks = geom.plot_layer(layer)
  File "/home/travis/build/yhat/ggplot/ggplot/geoms/stat_bin2d.py", line 16, in plot_layer
    plt.hist2d(x, y, cmap=plt.cm.Blues, **layer)
AttributeError: 'module' object has no attribute 'hist2d'
```

https://travis-ci.org/yhat/ggplot/jobs/17374706

So, the easiest fix would be to detect a older matplotlib version and raise a Exception/warning in stat_bin2d and also mark this test as not passing when matplotib is too old.

But maybe there is a different version, which works on matplotlib 1.1.1? I haven't had a look at matplotlibs internals...

@yarikoptic do you know something more about this issue?
